### ISSUE TITLE
Question: how to enter bootloader mode by software

### ISSUE THREAD

**Issue by joseangeljimenez** [mattairtech/ArduinoCore-samd#1]
According to the documentation, to enter bootloader mode you can press and hold button A while power cycling or resetting the board.

Assuming a program/sketch has been loaded with CDC-HID enabled, is it possible to enter the bootloader module by software, without power cycling the board?

Regards,
Jose

**Comment by mattairtech** [comment]
The arduino samd core enters the bootloader by erasing the first row of application area flash, then performing a software reset via NVIC_SystemReset(). See void banzai() in Reset.cpp. The bootloader resides at the beginning of flash and always executes first after any reset. In addition to checking for double-tap reset and boot button assertion, the bootloader checks the first word of the application section to see if it is erased (0xFFFFFFFF). Since banzai() erased this section, the bootloader will continue running. By comparison, the Arduino Leonardo used the watchdog timer and a magic number to enter the bootloader.

It would be possible to call the banzai() function from your sketch to initiate the bootloader (even without CDC enabled), however, this function is not a part of the API, and is not visible to the sketch. As a quick hack, you could #include "Reset.cpp", and:

`initiateReset(250);`
`tickReset();`

The call to tickReset() will in turn call banzai(). Perhaps there should be a more direct way to do this.
