### ISSUE TITLE
sam.h file missing

### ISSUE THREAD

**Issue by dunk8888** [mattairtech/ArduinoCore-samd#14]
Hi,how do i get rid of the sam.h error, its looking for that file and not finding it.

Is there a core for SAM-D witch has samd 9-10-11-21 etc or do i need to find cores for them seperatly,ile be messing around with some of these mcu as i want to move up from avr. Ime fairly new to programming and ime allways getting errors.I just need a good starting point so i can start using some of these mcu,mainly samd 11 and 21.Ime using arduino ide 1.8.5 ile be trying to use fastled and neopixel libraries with these mcu,are they supported with these libraries.cheers

**Comment by mattairtech** [comment]
Did you install this using Boards Manager in the Arduino IDE? The sam.h file is a part of the CMSIS-Atmel package (https://github.com/mattairtech/CMSIS-Atmel) which is installed automatically when using Boards Manager. It should be installed in <your localappdata path if using Windows>/Arduino15/packages/MattairTech_Arduino/tools/CMSIS-Atmel/1.0.0-mattairtech-2. There are other dependencies that are installed as well. Also, it is important to note that boards manager might not install/uninstall the core or tools properly if the contents of the arduino15 directory have been manually modified, so be sure to delete *all* manually installed/created folders (not just files), then try re-installing using Boards Manager, and make note of any errors.

**Comment by mattairtech** [comment]
To answer your second question, the D9 and D10 are subsets of the hardware present on the D11 (for example, no USB), and the D20 is a subset of the D21. It is far more likely that engineers/companies will buy these chips rather than enthusiasts, since the price difference is not much when buying single chip quantities or development boards. It should not be too much trouble for an engineer to modify the existing cores to support the D9, D10, and D20, but I wouldn't recommend these chips to enthusiasts.
