### ISSUE TITLE
Arduino core in PlatformIO IDE?

### ISSUE THREAD

**Issue by karu2003** [mattairtech/ArduinoCore-samd#6]
Good afternoon,

When there is support in PlatformIO?
PlatformIO IDE is better than Arduino IDE.
Maybe you have a tutorial on how to migrate to PlatformIO.

Thank you.
Andrew.

**Comment by mattairtech** [comment]
My plan for the past few months was to get this done by the end of August (50% chance of being done by August 10). I'm still not sure how much time it will take, otherwise I would have a better answer. I will likely be able to do it sooner if it does not take too long, otherwise it will have to wait until August when I am finished with a current hardware project. But, I have to do more research to figure that out. It looks like Making a custom framework for the custom core looks fairly straightforward. I'm not yet sure if I will also need to create a custom platform as well. Over the next several days as I have spare time, I will learn more and post here with a better time estimate.
